version: '3.8'

services:
  app:
    container_name: "my_project_app"
    build: .
    depends_on:
      - db
    working_dir: /src
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    container_name: "my_project_nginx"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs

  bot:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db


volumes:
  postgres-data:
