version: '3.8'

services:
  app:
    container_name: "my_project_app"
    build: .
    depends_on:
      - db
    working_dir: /src
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn web:app --host 0.0.0.0 --port 8000'
    networks:
      - guesser-network

  db:
    image: postgres:latest
    container_name: my_project_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - guesser-network

  nginx:
    image: nginx:latest
    container_name: my_project_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/root/Guesser/static
      - ./certs:/etc/nginx/certs
    networks:
      - guesser-network

  bot:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
    networks:
      - guesser-network

volumes:
  postgres-data:

networks:
  guesser-network:
    driver: bridge
